# Generated by Django 4.1.3 on 2022-11-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrocompra',
            fields=[
                ('producto_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(blank=True, max_length=45, null=True)),
                ('cantidad_producto', models.IntegerField(blank=True, null=True)),
                ('estado_producto', models.CharField(blank=True, max_length=45, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'carrocompra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('primernombre', models.CharField(blank=True, db_column='primerNombre', max_length=45, null=True)),
                ('segundonombre', models.CharField(db_column='segundoNombre', max_length=45)),
                ('apellidopaterno', models.CharField(blank=True, db_column='apellidoPaterno', max_length=45, null=True)),
                ('apellidomaterno', models.CharField(db_column='apellidoMaterno', max_length=45)),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('contraseña', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('primernombre', models.IntegerField(db_column='primerNombre', primary_key=True, serialize=False)),
                ('segundonombre', models.CharField(db_column='segundoNombre', max_length=45)),
                ('apellidopaterno', models.CharField(blank=True, db_column='apellidoPaterno', max_length=45, null=True)),
                ('apellidomaterno', models.CharField(blank=True, db_column='apellidoMaterno', max_length=45, null=True)),
                ('correo', models.EmailField(blank=True, max_length=45, null=True)),
                ('contraseña', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empleados',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(db_column='idProducto', primary_key=True, serialize=False)),
                ('nombreproducto', models.CharField(blank=True, db_column='nombreProducto', max_length=45, null=True)),
                ('precioproducto', models.CharField(blank=True, db_column='precioProducto', max_length=45, null=True)),
                ('cantidadproducto', models.CharField(blank=True, db_column='cantidadProducto', max_length=45, null=True)),
                ('descripcionproducto', models.CharField(blank=True, db_column='descripcionProducto', max_length=250, null=True)),
                ('estadoproducto', models.CharField(blank=True, db_column='estadoProducto', max_length=45, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.AutoField(db_column='idRol', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('idventas', models.PositiveIntegerField(db_column='idVentas', primary_key=True, serialize=False)),
                ('n_producto', models.CharField(blank=True, max_length=45, null=True)),
                ('c_producto', models.CharField(blank=True, max_length=45, null=True)),
                ('p_producto', models.CharField(blank=True, max_length=45, null=True)),
                ('d_producto', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ventas',
                'managed': False,
            },
        ),
    ]
